name: Update Gists

on:
  push:
    paths:
      - 'force-app/main/default/classes/*.cls'
      - 'force-app/main/default/flows/*.flow-meta.xml'

jobs:
  update_gists:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install gist
      run: sudo gem install gist
    - name: Update ListenerFlowController.cls --token $GIST_TOKEN
      env:
        GIST_TOKEN: ${{secrets.GIST_TOKEN}}
      run: gist -u cb4df0a6a0c1cbf630e81cf28c70000f force-app/main/default/classes/ListenerFlowController.cls
    - name: Update ListenerFlowControllerTest.cls --token $GIST_TOKEN
      env:
        GIST_TOKEN: ${{secrets.GIST_TOKEN}}
      run: gist -u e9a9b145e81aff8cf1021c848f2c1cbc force-app/main/default/classes/ListenerFlowControllerTest.cls
    - name: Update TestDataFactory.cls --token $GIST_TOKEN
      env:
        GIST_TOKEN: ${{secrets.GIST_TOKEN}}
      run: gist -u 8bd43794f17e72112704184ee04ddd7b force-app/main/default/classes/TestDataFactory.cls
    - name: Update Listener_Batch_Flow.flow-meta.xml --token $GIST_TOKEN
      env:
        GIST_TOKEN: ${{secrets.GIST_TOKEN}}
      run: gist -u 0bb5a6600c34799382b42c1998e9fbf9 force-app/main/default/flows/Listener_Batch_Flow.flow-meta.xml
    - name: Update Listener_Configuration_Main_Flow.flow-meta.xml --token $GIST_TOKEN
      env:
        GIST_TOKEN: ${{secrets.GIST_TOKEN}}
      run: gist -u 6908a3176b423bee76b216ab33948492 force-app/main/default/flows/Listener_Configuration_Main_Flow.flow-meta.xml
    - name: Update Listener_Flow_Sub_Flow.flow-meta.xml --token $GIST_TOKEN
      env:
        GIST_TOKEN: ${{secrets.GIST_TOKEN}}
      run: gist -u 0cb1f81bb578cc10cd4f9c0189cc1793 force-app/main/default/flows/Listener_Flow_Sub_Flow.flow-meta.xml
