name: Update Gists

on:
  push:
    paths:
      - 'force-app/main/default/classes/*.cls'
      - 'force-app/main/default/flows/*.flow-meta.xml'

jobs:
  update_gists:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '16'
      GH_TOKEN: ${{ secrets.GIST_TOKEN }}
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Install gist-cli
      run: npm install -g gist-cli
    - name: Update ListenerFlowController.cls
      run: gist-cli update cb4df0a6a0c1cbf630e81cf28c70000f force-app/main/default/classes/ListenerFlowController.cls
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
    - name: Update ListenerFlowControllerTest.cls
      run: gist-cli update e9a9b145e81aff8cf1021c848f2c1cbc force-app/main/default/classes/ListenerFlowControllerTest.cls
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
    - name: Update TestDataFactory.cls
      run: gist-cli update 8bd43794f17e72112704184ee04ddd7b force-app/main/default/classes/TestDataFactory.cls
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
    - name: Update Listener_Batch_Flow.flow-meta.xml
      run: gist-cli update 0bb5a6600c34799382b42c1998e9fbf9 force-app/main/default/flows/Listener_Batch_Flow.flow-meta.xml
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
    - name: Update Listener_Configuration_Main_Flow.flow-meta.xml
      run: gist-cli update 6908a3176b423bee76b216ab33948492 force-app/main/default/flows/Listener_Configuration_Main_Flow.flow-meta.xml
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
    - name: Update Listener_Flow_Sub_Flow.flow-meta.xml
      run: gist-cli update 0cb1f81bb578cc10cd4f9c0189cc1793 force-app/main/default/flows/Listener_Flow_Sub_Flow.flow-meta.xml
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
