name: Update Gists

on:
  push:
    paths:
      - 'force-app/main/default/classes/*.cls'
      - 'force-app/main/default/flows/*.flow-meta.xml'
      - 'force-app/main/default/objects/**/*'

jobs:
  update_gists:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '16'
      GH_TOKEN: ${{ secrets.GIST_TOKEN }}
    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: pip install -r requirements.txt  # Assuming you have a requirements.txt

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Parse XML and Convert to JSON
        run: python parse_and_convert.py  # This will generate gist_content.json

      - name: Update Gists
        run: |
          gh gist edit ef3ccbd0692b0c633f5428168442dd9f --add gist_content.json
