name: Update Gists

on:
  push:
    paths:
      - 'force-app/main/default/classes/*.cls'
      - 'force-app/main/default/flows/*.flow-meta.xml'
      - 'force-app/main/default/objects/**/*'

jobs:
  update_gists:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '16'
      GH_TOKEN: ${{ secrets.GIST_TOKEN }}
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Update Gists
      run: |
        gh gist edit cb4df0a6a0c1cbf630e81cf28c70000f --add force-app/main/default/classes/ListenerFlowController.cls
        gh gist edit 6908a3176b423bee76b216ab33948492 --add force-app/main/default/classes/ListenerFlowControllerTest.cls
        gh gist edit 6ff9d325ef68cf17d3c0688fc4461a1a --add force-app/main/default/classes/TestDataFactory.cls
        gh gist edit 0bb5a6600c34799382b42c1998e9fbf9 --add force-app/main/default/flows/Listener_Batch_Flow.flow-meta.xml
        gh gist edit 8bd43794f17e72112704184ee04ddd7b --add force-app/main/default/flows/Listener_Configuration_Main_Flow.flow-meta.xml
        gh gist edit 0cb1f81bb578cc10cd4f9c0189cc1793 --add force-app/main/default/flows/Listener_Flow_Sub_Flow.flow-meta.xml
        output_file="gist_content.txt"
        echo "" > $output_file
        for dir in $(find force-app/main/default/objects -mindepth 1 -maxdepth 1 -type d); do
          object_name=$(basename $dir)
          echo "$object_name" >> $output_file
          for field_file in $(find $dir/fields -type f -name '*.field-meta.xml'); do
            field_name=$(basename $field_file .field-meta.xml)
            echo "--$field_name" >> $output_file
            awk -F'[<>]' '
              /<[^/]/ {
                tag=$2;
                value=$3;
                if (tag == "fullName") {
                  tag = "API Name";
                }
                printf "------%s: %s\n", tag, value;
              }
            ' $field_file >> $output_file
          done
        done
        gh gist edit ef3ccbd0692b0c633f5428168442dd9f --add $output_file